public class NotExistIDException extends Exception {
    public NotExistIDException() {}

    public NotExistIDException(String message) {
                             1번 super(message);
    }
}
public class WrongPasswordException extends Exception{
    public WrongPasswordException() {}

    public WrongPasswordException(String message) {
                               2번 super(message);
    }
}
public class LoginExample {
    public static void main(String[] args) {
        try {
            login("white", "12345");
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }

        try {
            login("blue", "54321");
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }

    public static void login(String id, String password) 3번 throws Exception {
        //id가 blue가 아니라면 NotExistIDException 을 발생시킴
        if(!id.equals("blue")) {
                           4번 throw new NotExistIdException("아이디가 존재하지않습니다.")
        }

        //password가 12345가 아니라면 WrongPasswordException 을 발생시킴
        if(!password.equals("12345")) {
                           5번 throw new WrongPasswordException("패스워드가 틀립니다.")
        }


    }
}

